name: geo_env
channels:
  - conda-forge
  - pytorch
dependencies:
  - appnope=0.1.4
  - asttokens=2.4.1
  - aws-c-auth=0.7.22
  - aws-c-cal=0.7.1
  - aws-c-common=0.9.23
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.2
  - aws-c-io=0.14.10
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.6.0
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.27.3
  - aws-sdk-cpp=1.11.329
  - azure-core-cpp=1.12.0
  - azure-identity-cpp=1.8.0
  - azure-storage-blobs-cpp=12.11.0
  - azure-storage-common-cpp=12.6.0
  - azure-storage-files-datalake-cpp=12.10.0
  - blosc=1.21.6
  - branca=0.7.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.32.2
  - ca-certificates=2024.7.4
  - cairo=1.18.0
  - certifi=2024.7.4
  - cffi=1.16.0
  - cfitsio=4.4.1
  - charset-normalizer=3.3.2
  - comm=0.2.2
  - contourpy=1.2.1
  - cycler=0.12.1
  - debugpy=1.8.2
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.0.1
  - expat=2.6.2
  - fmt=10.2.1
  - folium=0.17.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.53.1
  - freetype=2.12.1
  - freexl=2.0.0
  - gdal=3.9.1
  - geographiclib=2.0
  - geopandas=1.0.1
  - geopandas-base=1.0.1
  - geopy=2.4.1
  - geos=3.12.2
  - geotiff=1.7.3
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.7.1
  - h2=4.1.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.7
  - importlib-metadata=8.0.0
  - importlib_metadata=8.0.0
  - ipykernel=6.29.5
  - ipython=8.26.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - json-c=0.17
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - kealib=1.5.3
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libarchive=3.7.4
  - libarrow=17.0.0
  - libarrow-acero=17.0.0
  - libarrow-dataset=17.0.0
  - libarrow-substrait=17.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.8.0
  - libcxx=18.1.8
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgdal=3.9.1
  - libgdal-core=3.9.1
  - libgdal-fits=3.9.1
  - libgdal-grib=3.9.1
  - libgdal-hdf4=3.9.1
  - libgdal-hdf5=3.9.1
  - libgdal-jp2openjpeg=3.9.1
  - libgdal-kea=3.9.1
  - libgdal-netcdf=3.9.1
  - libgdal-pdf=3.9.1
  - libgdal-pg=3.9.1
  - libgdal-postgisraster=3.9.1
  - libgdal-tiledb=3.9.1
  - libgdal-xls=3.9.1
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.80.3
  - libgoogle-cloud=2.26.0
  - libgoogle-cloud-storage=2.26.0
  - libgrpc=1.62.2
  - libiconv=1.17
  - libintl=0.22.5
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libopenblas=0.3.27
  - libparquet=17.0.0
  - libpng=1.6.43
  - libpq=16.3
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialite=5.1.0
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libutf8proc=2.8.0
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxml2=2.12.7
  - libzip=1.10.1
  - libzlib=1.3.1
  - llvm-openmp=18.1.8
  - lz4-c=1.9.4
  - lzo=2.10
  - mapclassify=2.6.1
  - markupsafe=2.1.5
  - matplotlib-base=3.9.1
  - matplotlib-inline=0.1.7
  - minizip=4.0.7
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.3
  - nspr=4.35
  - nss=3.102
  - numpy=2.0.0
  - openjpeg=2.5.2
  - openssl=3.3.1
  - orc=2.0.1
  - packaging=24.1
  - pandas=2.2.2
  - parso=0.8.4
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.0
  - pixman=0.43.4
  - platformdirs=4.2.2
  - poppler=24.07.0
  - poppler-data=0.4.12
  - postgresql=16.3
  - proj=9.4.1
  - prompt-toolkit=3.0.47
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py4j=0.10.9.7
  - pyarrow=17.0.0
  - pyarrow-core=17.0.0
  - pycparser=2.22
  - pygments=2.18.0
  - pyogrio=0.9.0
  - pyparsing=3.1.2
  - pyproj=3.6.1
  - pysocks=1.7.1
  - pyspark=3.5.1
  - python=3.12.4
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.12
  - pytz=2024.1
  - pyzmq=26.0.3
  - qhull=2020.2
  - re2=2023.09.01
  - readline=8.2
  - requests=2.32.3
  - scikit-learn=1.5.1
  - scipy=1.14.0
  - setuptools=71.0.4
  - shapely=2.0.5
  - six=1.16.0
  - snappy=1.2.1
  - spdlog=1.13.0
  - sqlite=3.46.0
  - stack_data=0.6.2
  - threadpoolctl=3.5.0
  - tiledb=2.24.2
  - tk=8.6.13
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzcode=2024a
  - tzdata=2024a
  - uriparser=0.9.8
  - urllib3=2.2.2
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xerces-c=3.2.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xyzservices=2024.6.0
  - xz=5.2.6
  - zeromq=4.3.5
  - zipp=3.19.2
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
